### ISSUE TITLE
Periodic crash

### ISSUE THREAD

**Issue by plitewaikato** [superhawk610/multicast#41] opened 2018-01-11 19:41 UTC
Hi all,

On my two Ubuntu and Debian machines Multicast works great, although after about fifteen minutes of operation the process crashes with the below error:

```
/usr/lib/node_modules/multicast/node_modules/castv2/lib/client.js:128
  this.ps.send(buf);
          ^

TypeError: Cannot read property 'send' of null
    at Client.send (/usr/lib/node_modules/multicast/node_modules/castv2/lib/client.js:128:11)
    at Channel.send (/usr/lib/node_modules/multicast/node_modules/castv2/lib/channel.js:34:12)
    at Timeout.d.pulse.setInterval [as _onTimeout] (/usr/lib/node_modules/multicast/app/lib/connection.js:51:32)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

The Chromecasts continue to display the last dashboard loaded on them, and reconnect when Multicast is relaunched.  I'm simply keeping the processes alive at the moment, but it would be great to fix this.

**Comment by superhawk610** [comment] 2018-01-11 20:18
I had this exact error reported to me via email:

![muticast](https://user-images.githubusercontent.com/18172185/34845034-9be883cc-f6e1-11e7-8ee2-d5daad7e2cb5.png)

Here's the relevant portion of code from Multicast:
```js
// app/lib/connection.js

// line 23
d.heartbeat = client.createChannel(
  'sender-0',
  'receiver-0',
  'urn:x-cast:com.google.cast.tp.heartbeat',
  'JSON'
)

...

// line 41
d.pulse = setInterval(() => {
  d.missedHeartbeats++
  if (d.missedHeartbeats > 6) {
    // receiver has been offline for more than 30 seconds
    d.status = 'offline' // mark receiver as offline
    clearInterval(d.pulse) // stop checking for pulse :(
    func.addError(
      d,
      'Receiver missed too many heartbeats, it is likely offline.'
    )
  } else d.heartbeat.send({ type: 'PING' })
}, 5 * 1000)
```

If I'm interpreting this correctly, this means that `d.heartbeat` is equivalent to `this.ps` from the library code, and for whatever reason is being set to null.

Chromecasts require sender devices (in this case, Multicast) to maintain a 'heartbeat', literally sending a message containing *PING* every 5 seconds and replying with *PONG*. It looks like this is going awry somewhere, but it seems like an error with the underlying node_mdns framework.

**Comment by jonty-comp** [comment] 2018-01-15 13:20
I experienced this once or twice while setting things up last week, but it doesn't seem to have triggered again since I stopped changing configurations. (now i'm developing what's actually on the screen instead of the screen itself!)  Not sure if that's related or if something else is triggering it.

**Comment by ocelotsloth** [comment] 2018-01-15 13:25
Similar to @jonty-comp, I get this error whenever I **add a new Chromecast**. It always needs a restart in order to properly initialize the device for some reason.

**Comment by superhawk610** [comment] 2018-01-15 14:43
@plitewaikato can you confirm that this issue has stopped occurring now that your device(s) have been registered?

@ocelotsloth That's likely what is causing it, the app attempts to keep a running store of all information for active devices and something is likely not being saved correctly.

**Comment by plitewaikato** [comment] 2018-01-15 21:41
Registering a device causes Multicast to become flakey and register this
error, I habitually restart the service after adding a device and it does
indeed behave normally after that.

**Comment by drampelt** [comment] 2018-02-20 15:59
I've had this happen running on a single-cored Raspberry Pi Zero, performing any action on the web interface uses 100% of the CPU for a few seconds and then the Chromecasts disconnect because they miss the heartbeat. I'm assuming this is because the CPU is hogged by the web interface and it can't maintain a connection to it or something. I just added a try/catch around that section and now the Chromecasts reconnect a few seconds later so it's not a huge deal.

**Comment by superhawk610** [comment] 2019-03-06 01:06
I'm closing all `v2.x` issues that are no longer relevant to the upcoming v3.0 release. The underlying framework is changing so drastically that it's unlikely this bug will be reproducible. Feel free to comment further if this issue persists in v3.0.

**Closed by superhawk610** 2019-03-06 01:06 UTC
Labels: bug, help wanted, v2.x
