### ISSUE TITLE
Only alerts

### ISSUE THREAD

**Issue by starrco** [superhawk610/multicast#52] opened 2019-02-09 16:10 UTC
Hi,
I've used this project recently at home and it worked well enough.  Now I'm trying to use it at work, and I only get alerts and a white screen.  I'm not a JS/node guy and I'm not sure where to start.  I have determined that no content is being sent, only JS/CSS and a mostly empty "toast" div.  The "title" also comes through.  I've used some very basic channels, such as google.com, static images, etc.  The title changes, but the screen remains white.  Alerts work great.  I thought I was on to something in app/routes/devices.js, but it seems I'm not getting the setup page, rather I'm getting the right page with no content. :(
Can you give me a push in the right direction?
Thank you!

**Comment by superhawk610** [comment] 2019-02-13 19:32
Unfortunately Chromecast apps can be somewhat of a pain to debug, as you've no doubt found already. The fact that it launches to a white screen would seem to indicate that the error isn't occurring in MultiCast but somewhere in your network, possibly due to different subnets not talking to each other correctly?

Try adding the built-in message channel `http://{MULTICAST_HOST_IP}:3944/message` and let me know what sort of results you get on your Chromecast display. It would also be helpful to check out the remote device debugger and see exactly what the Chromecast is seeing - open up `chrome://inspect` on a device on the same subnet and click **Inspect** to take a look at the DOM and console for that Chromecast.

Feel free to post logs or screenshots in this thread, I've been away from the project for a bit so it would help me too :)

**Comment by superhawk610** [comment] 2019-03-06 01:05
I'm closing all `v2.x` issues that are no longer relevant to the upcoming v3.0 release. The underlying framework is changing so drastically that it's unlikely this bug will be reproducible. Feel free to comment further if this issue persists in v3.0.

**Closed** 2019-03-06 01:04 UTC
Labels: v2.x
